waypoints:
  classroom_1:
    label: 1강의실
    x: -0.2369
    y: 5.347
    yaw: -0.9193
  classroom_2:
    label: 2강의실
    x: -0.4945
    y: 11.5831
    yaw: -1.0432
  classroom_3:
    label: 3강의실
    x: -0.6911
    y: 17.3775
    yaw: -0.9752
  classroom_4:
    label: 4강의실
    x: -0.9164
    y: 23.5651
    yaw: -0.8866
  classroom_5:
    label: 5강의실
    x: 0.5596
    y: 20.6608
    yaw: -2.0854
  counseling_1:
    label: 상담실1
    x: 7.7922
    y: 6.6732
    yaw: -2.201
  counseling_2:
    label: 상담실2
    x: 7.8918
    y: 4.9177
    yaw: -3.0637
  counter:
    label: 카운터
    x: 4.6206
    y: 3.0
    yaw: -3.0682
  home_robot1:
    label: 로봇1 홈
    x: -0.1111
    y: 0.0123
    yaw: -1.5708
  home_robot1_staging:
    label: 로봇1 홈 스테이징
    x: -0.18
    y: 0.9123
    yaw: -1.5708
  home_robot2:
    label: 로봇2 홈
    x: 0.385
    y: 0.0123
    yaw: -1.588
  home_robot2_staging:
    label: 로봇2 홈 스테이징
    x: 0.385
    y: 0.9123
    yaw: -1.588
  intensive_counseling_1:
    label: 집중상담실1
    x: 6.6684
    y: 8.5656
    yaw: -3.111
  intensive_counseling_2:
    label: 집중상담실2
    x: 6.598
    y: 2.8539
    yaw: 2.8927
  multi:
    label: 멀티룸
    x: 4.99
    y: 13.5636
    yaw: -1.4761
  vice_principal:
    label: 회의실
    x: 6.4243
    y: 10.3973
    yaw: -2.6607
  glass_entry:
    label: 유리구간 진입
    x: -0.2
    y: 2.65
    yaw: 0.0
  glass_exit:
    label: 유리구간 탈출
    x: 2.2158
    y: 2.7579
    yaw: 0.0
